In [1]:
from datetime import time
import pandas as pd

In [2]:
df = pd.read_csv("cluster0_df.csv")

In [3]:
df = df[["Order_Date", "Number of Orders"]]

In [4]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])
df

   Order_Date  Number of Orders
0  2022-03-01                67
1  2022-03-02                 1
2  2022-03-03                51
3  2022-03-04                 1
4  2022-03-05                57
5  2022-03-07                61
6  2022-03-09                59
7  2022-03-11                65
8  2022-03-12                 1
9  2022-03-13                61
10 2022-03-15                56
11 2022-03-16                 1
12 2022-03-17                59
13 2022-03-18                 1
14 2022-03-19                60
15 2022-03-20                 1
16 2022-03-21                62
17 2022-03-23                 1
18 2022-03-24                61
19 2022-03-26                66
20 2022-03-28                58
21 2022-03-29                 1
22 2022-03-30                61
23 2022-04-01                65
24 2022-04-03                62
25 2022-04-04                 1
26 2022-04-05                55

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_Date        27 non-null     datetime64[ns]
 1   Number of Orders  27 non-null     int64
dtypes: datetime64[ns](1), int64(1)
memory usage: 564.0 bytes

In [6]:
daterange = pd.date_range(start="2022-03-01", end="2022-04-06")

In [7]:
df.set_index("Order_Date", inplace=True)

In [8]:
df = df.reindex(daterange,fill_value=0)

In [10]:
df.reset_index(inplace=True)
df.columns = ["Order_Date", "Number of Orders"]

In [11]:
df

   Order_Date  Number of Orders
0  2022-03-01                67
1  2022-03-02                 1
2  2022-03-03                51
3  2022-03-04                 1
4  2022-03-05                57
5  2022-03-06                 0
6  2022-03-07                61
7  2022-03-08                 0
8  2022-03-09                59
9  2022-03-10                 0
10 2022-03-11                65
11 2022-03-12                 1
12 2022-03-13                61
13 2022-03-14                 0
14 2022-03-15                56
15 2022-03-16                 1
16 2022-03-17                59
17 2022-03-18                 1
18 2022-03-19                60
19 2022-03-20                 1
20 2022-03-21                62
21 2022-03-22                 0
22 2022-03-23                 1
23 2022-03-24                61
24 2022-03-25                 0
25 2022-03-26                66
26 2022-03-27                 0
27 2022-03-28                58
28 2022-03-29                 1
29 2022-03-30                61
30 2022-03-31                 0
31 2022-04-01                65
32 2022-04-02                 0
33 2022-04-03                62
34 2022-04-04                 1
35 2022-04-05                55
36 2022-04-06                 0